[theme]
primaryColor = "#F63366"
backgroundColor = "#0E1117"  # Dark background color
secondaryBackgroundColor = "#31333F"  # Darker background for sidebar
textColor = "#FFFFFF"  # White text
font = "sans serif"
